/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthExamRouteImport } from './routes/_auth/_exam'
import { Route as AuthIndividuRouteImport } from './routes/_auth/_individu'
import { Route as AuthOrganizationRouteImport } from './routes/_auth/_organization'
import { Route as AuthOrganizationAndIndividuRouteImport } from './routes/_auth/_organization-and-individu'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthOrganizationAndIndividuProfileRouteImport } from './routes/_auth/_organization-and-individu/profile'
import { Route as AuthCreateOrganizationIndexRouteImport } from './routes/_auth/create-organization/index'
import { Route as GuestForgotPasswordIndexRouteImport } from './routes/_guest/forgot-password/index'
import { Route as GuestLoginIndexRouteImport } from './routes/_guest/login/index'
import { Route as GuestRegisterIndexRouteImport } from './routes/_guest/register/index'
import { Route as GuestResetPasswordIndexRouteImport } from './routes/_guest/reset-password/index'
import { Route as AuthIndividuPortalIndexRouteImport } from './routes/_auth/_individu/portal/index'
import { Route as AuthIndividuTestHistoryIndexRouteImport } from './routes/_auth/_individu/test-history/index'
import { Route as AuthIndividuTestIndexRouteImport } from './routes/_auth/_individu/test/index'
import { Route as AuthOrganizationAndIndividuBillingIndexRouteImport } from './routes/_auth/_organization-and-individu/billing/index'
import { Route as AuthOrganizationAndIndividuProfileIndexRouteImport } from './routes/_auth/_organization-and-individu/profile/index'
import { Route as AuthOrganizationDashboardIndexRouteImport } from './routes/_auth/_organization/dashboard/index'
import { Route as AuthOrganizationMembersIndexRouteImport } from './routes/_auth/_organization/members/index'
import { Route as AuthOrganizationSettingsIndexRouteImport } from './routes/_auth/_organization/settings/index'
import { Route as GuestRegisterOrganizationIndexRouteImport } from './routes/_guest/register/organization/index'
import { Route as GuestRegisterVerifyEmailIndexRouteImport } from './routes/_guest/register/verify-email/index'
import { Route as AuthExamExamTestIdIndexRouteImport } from './routes/_auth/_exam/exam/$testId/index'
import { Route as AuthOrganizationAndIndividuProfileReferralIndexRouteImport } from './routes/_auth/_organization-and-individu/profile/referral/index'
import { Route as GuestRegisterInviteTokenIndexRouteImport } from './routes/_guest/register/invite/$token/index'
import { Route as AuthOrganizationAndIndividuJointInviteTokenIndexRouteImport } from './routes/_auth/_organization-and-individu/joint/invite/$token/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthExamRoute = AuthExamRouteImport.update({
  id: '/_exam',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIndividuRoute = AuthIndividuRouteImport.update({
  id: '/_individu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationRoute = AuthOrganizationRouteImport.update({
  id: '/_organization',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationAndIndividuRoute =
  AuthOrganizationAndIndividuRouteImport.update({
    id: '/_organization-and-individu',
    getParentRoute: () => AuthRoute,
  } as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationAndIndividuProfileRoute =
  AuthOrganizationAndIndividuProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthOrganizationAndIndividuRoute,
  } as any)
const AuthCreateOrganizationIndexRoute =
  AuthCreateOrganizationIndexRouteImport.update({
    id: '/create-organization/',
    path: '/create-organization/',
    getParentRoute: () => AuthRoute,
  } as any)
const GuestForgotPasswordIndexRoute =
  GuestForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => GuestRoute,
  } as any)
const GuestLoginIndexRoute = GuestLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterIndexRoute = GuestRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestResetPasswordIndexRoute = GuestResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => GuestRoute,
} as any)
const AuthIndividuPortalIndexRoute = AuthIndividuPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => AuthIndividuRoute,
} as any)
const AuthIndividuTestHistoryIndexRoute =
  AuthIndividuTestHistoryIndexRouteImport.update({
    id: '/test-history/',
    path: '/test-history/',
    getParentRoute: () => AuthIndividuRoute,
  } as any)
const AuthIndividuTestIndexRoute = AuthIndividuTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => AuthIndividuRoute,
} as any)
const AuthOrganizationAndIndividuBillingIndexRoute =
  AuthOrganizationAndIndividuBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthOrganizationAndIndividuRoute,
  } as any)
const AuthOrganizationAndIndividuProfileIndexRoute =
  AuthOrganizationAndIndividuProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrganizationAndIndividuProfileRoute,
  } as any)
const AuthOrganizationDashboardIndexRoute =
  AuthOrganizationDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthOrganizationRoute,
  } as any)
const AuthOrganizationMembersIndexRoute =
  AuthOrganizationMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthOrganizationRoute,
  } as any)
const AuthOrganizationSettingsIndexRoute =
  AuthOrganizationSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthOrganizationRoute,
  } as any)
const GuestRegisterOrganizationIndexRoute =
  GuestRegisterOrganizationIndexRouteImport.update({
    id: '/register/organization/',
    path: '/register/organization/',
    getParentRoute: () => GuestRoute,
  } as any)
const GuestRegisterVerifyEmailIndexRoute =
  GuestRegisterVerifyEmailIndexRouteImport.update({
    id: '/register/verify-email/',
    path: '/register/verify-email/',
    getParentRoute: () => GuestRoute,
  } as any)
const AuthExamExamTestIdIndexRoute = AuthExamExamTestIdIndexRouteImport.update({
  id: '/exam/$testId/',
  path: '/exam/$testId/',
  getParentRoute: () => AuthExamRoute,
} as any)
const AuthOrganizationAndIndividuProfileReferralIndexRoute =
  AuthOrganizationAndIndividuProfileReferralIndexRouteImport.update({
    id: '/referral/',
    path: '/referral/',
    getParentRoute: () => AuthOrganizationAndIndividuProfileRoute,
  } as any)
const GuestRegisterInviteTokenIndexRoute =
  GuestRegisterInviteTokenIndexRouteImport.update({
    id: '/register/invite/$token/',
    path: '/register/invite/$token/',
    getParentRoute: () => GuestRoute,
  } as any)
const AuthOrganizationAndIndividuJointInviteTokenIndexRoute =
  AuthOrganizationAndIndividuJointInviteTokenIndexRouteImport.update({
    id: '/joint/invite/$token/',
    path: '/joint/invite/$token/',
    getParentRoute: () => AuthOrganizationAndIndividuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/profile': typeof AuthOrganizationAndIndividuProfileRouteWithChildren
  '/create-organization/': typeof AuthCreateOrganizationIndexRoute
  '/forgot-password/': typeof GuestForgotPasswordIndexRoute
  '/login/': typeof GuestLoginIndexRoute
  '/register/': typeof GuestRegisterIndexRoute
  '/reset-password/': typeof GuestResetPasswordIndexRoute
  '/portal/': typeof AuthIndividuPortalIndexRoute
  '/test-history/': typeof AuthIndividuTestHistoryIndexRoute
  '/test/': typeof AuthIndividuTestIndexRoute
  '/billing/': typeof AuthOrganizationAndIndividuBillingIndexRoute
  '/profile/': typeof AuthOrganizationAndIndividuProfileIndexRoute
  '/dashboard/': typeof AuthOrganizationDashboardIndexRoute
  '/members/': typeof AuthOrganizationMembersIndexRoute
  '/settings/': typeof AuthOrganizationSettingsIndexRoute
  '/register/organization/': typeof GuestRegisterOrganizationIndexRoute
  '/register/verify-email/': typeof GuestRegisterVerifyEmailIndexRoute
  '/exam/$testId/': typeof AuthExamExamTestIdIndexRoute
  '/profile/referral/': typeof AuthOrganizationAndIndividuProfileReferralIndexRoute
  '/register/invite/$token/': typeof GuestRegisterInviteTokenIndexRoute
  '/joint/invite/$token/': typeof AuthOrganizationAndIndividuJointInviteTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/create-organization': typeof AuthCreateOrganizationIndexRoute
  '/forgot-password': typeof GuestForgotPasswordIndexRoute
  '/login': typeof GuestLoginIndexRoute
  '/register': typeof GuestRegisterIndexRoute
  '/reset-password': typeof GuestResetPasswordIndexRoute
  '/portal': typeof AuthIndividuPortalIndexRoute
  '/test-history': typeof AuthIndividuTestHistoryIndexRoute
  '/test': typeof AuthIndividuTestIndexRoute
  '/billing': typeof AuthOrganizationAndIndividuBillingIndexRoute
  '/profile': typeof AuthOrganizationAndIndividuProfileIndexRoute
  '/dashboard': typeof AuthOrganizationDashboardIndexRoute
  '/members': typeof AuthOrganizationMembersIndexRoute
  '/settings': typeof AuthOrganizationSettingsIndexRoute
  '/register/organization': typeof GuestRegisterOrganizationIndexRoute
  '/register/verify-email': typeof GuestRegisterVerifyEmailIndexRoute
  '/exam/$testId': typeof AuthExamExamTestIdIndexRoute
  '/profile/referral': typeof AuthOrganizationAndIndividuProfileReferralIndexRoute
  '/register/invite/$token': typeof GuestRegisterInviteTokenIndexRoute
  '/joint/invite/$token': typeof AuthOrganizationAndIndividuJointInviteTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/_exam': typeof AuthExamRouteWithChildren
  '/_auth/_individu': typeof AuthIndividuRouteWithChildren
  '/_auth/_organization': typeof AuthOrganizationRouteWithChildren
  '/_auth/_organization-and-individu': typeof AuthOrganizationAndIndividuRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_guest/': typeof GuestIndexRoute
  '/_auth/_organization-and-individu/profile': typeof AuthOrganizationAndIndividuProfileRouteWithChildren
  '/_auth/create-organization/': typeof AuthCreateOrganizationIndexRoute
  '/_guest/forgot-password/': typeof GuestForgotPasswordIndexRoute
  '/_guest/login/': typeof GuestLoginIndexRoute
  '/_guest/register/': typeof GuestRegisterIndexRoute
  '/_guest/reset-password/': typeof GuestResetPasswordIndexRoute
  '/_auth/_individu/portal/': typeof AuthIndividuPortalIndexRoute
  '/_auth/_individu/test-history/': typeof AuthIndividuTestHistoryIndexRoute
  '/_auth/_individu/test/': typeof AuthIndividuTestIndexRoute
  '/_auth/_organization-and-individu/billing/': typeof AuthOrganizationAndIndividuBillingIndexRoute
  '/_auth/_organization-and-individu/profile/': typeof AuthOrganizationAndIndividuProfileIndexRoute
  '/_auth/_organization/dashboard/': typeof AuthOrganizationDashboardIndexRoute
  '/_auth/_organization/members/': typeof AuthOrganizationMembersIndexRoute
  '/_auth/_organization/settings/': typeof AuthOrganizationSettingsIndexRoute
  '/_guest/register/organization/': typeof GuestRegisterOrganizationIndexRoute
  '/_guest/register/verify-email/': typeof GuestRegisterVerifyEmailIndexRoute
  '/_auth/_exam/exam/$testId/': typeof AuthExamExamTestIdIndexRoute
  '/_auth/_organization-and-individu/profile/referral/': typeof AuthOrganizationAndIndividuProfileReferralIndexRoute
  '/_guest/register/invite/$token/': typeof GuestRegisterInviteTokenIndexRoute
  '/_auth/_organization-and-individu/joint/invite/$token/': typeof AuthOrganizationAndIndividuJointInviteTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$token'
    | '/profile'
    | '/create-organization/'
    | '/forgot-password/'
    | '/login/'
    | '/register/'
    | '/reset-password/'
    | '/portal/'
    | '/test-history/'
    | '/test/'
    | '/billing/'
    | '/profile/'
    | '/dashboard/'
    | '/members/'
    | '/settings/'
    | '/register/organization/'
    | '/register/verify-email/'
    | '/exam/$testId/'
    | '/profile/referral/'
    | '/register/invite/$token/'
    | '/joint/invite/$token/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/portal'
    | '/test-history'
    | '/test'
    | '/billing'
    | '/profile'
    | '/dashboard'
    | '/members'
    | '/settings'
    | '/register/organization'
    | '/register/verify-email'
    | '/exam/$testId'
    | '/profile/referral'
    | '/register/invite/$token'
    | '/joint/invite/$token'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/_exam'
    | '/_auth/_individu'
    | '/_auth/_organization'
    | '/_auth/_organization-and-individu'
    | '/invite/$token'
    | '/_guest/'
    | '/_auth/_organization-and-individu/profile'
    | '/_auth/create-organization/'
    | '/_guest/forgot-password/'
    | '/_guest/login/'
    | '/_guest/register/'
    | '/_guest/reset-password/'
    | '/_auth/_individu/portal/'
    | '/_auth/_individu/test-history/'
    | '/_auth/_individu/test/'
    | '/_auth/_organization-and-individu/billing/'
    | '/_auth/_organization-and-individu/profile/'
    | '/_auth/_organization/dashboard/'
    | '/_auth/_organization/members/'
    | '/_auth/_organization/settings/'
    | '/_guest/register/organization/'
    | '/_guest/register/verify-email/'
    | '/_auth/_exam/exam/$testId/'
    | '/_auth/_organization-and-individu/profile/referral/'
    | '/_guest/register/invite/$token/'
    | '/_auth/_organization-and-individu/joint/invite/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_exam': {
      id: '/_auth/_exam'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthExamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_individu': {
      id: '/_auth/_individu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthIndividuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_organization': {
      id: '/_auth/_organization'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthOrganizationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_organization-and-individu': {
      id: '/_auth/_organization-and-individu'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthOrganizationAndIndividuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_organization-and-individu/profile': {
      id: '/_auth/_organization-and-individu/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthOrganizationAndIndividuProfileRouteImport
      parentRoute: typeof AuthOrganizationAndIndividuRoute
    }
    '/_auth/create-organization/': {
      id: '/_auth/create-organization/'
      path: '/create-organization'
      fullPath: '/create-organization/'
      preLoaderRoute: typeof AuthCreateOrganizationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/forgot-password/': {
      id: '/_guest/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof GuestForgotPasswordIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login/': {
      id: '/_guest/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof GuestLoginIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register/': {
      id: '/_guest/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof GuestRegisterIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password/': {
      id: '/_guest/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof GuestResetPasswordIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/_individu/portal/': {
      id: '/_auth/_individu/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthIndividuPortalIndexRouteImport
      parentRoute: typeof AuthIndividuRoute
    }
    '/_auth/_individu/test-history/': {
      id: '/_auth/_individu/test-history/'
      path: '/test-history'
      fullPath: '/test-history/'
      preLoaderRoute: typeof AuthIndividuTestHistoryIndexRouteImport
      parentRoute: typeof AuthIndividuRoute
    }
    '/_auth/_individu/test/': {
      id: '/_auth/_individu/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof AuthIndividuTestIndexRouteImport
      parentRoute: typeof AuthIndividuRoute
    }
    '/_auth/_organization-and-individu/billing/': {
      id: '/_auth/_organization-and-individu/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthOrganizationAndIndividuBillingIndexRouteImport
      parentRoute: typeof AuthOrganizationAndIndividuRoute
    }
    '/_auth/_organization-and-individu/profile/': {
      id: '/_auth/_organization-and-individu/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthOrganizationAndIndividuProfileIndexRouteImport
      parentRoute: typeof AuthOrganizationAndIndividuProfileRoute
    }
    '/_auth/_organization/dashboard/': {
      id: '/_auth/_organization/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthOrganizationDashboardIndexRouteImport
      parentRoute: typeof AuthOrganizationRoute
    }
    '/_auth/_organization/members/': {
      id: '/_auth/_organization/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthOrganizationMembersIndexRouteImport
      parentRoute: typeof AuthOrganizationRoute
    }
    '/_auth/_organization/settings/': {
      id: '/_auth/_organization/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthOrganizationSettingsIndexRouteImport
      parentRoute: typeof AuthOrganizationRoute
    }
    '/_guest/register/organization/': {
      id: '/_guest/register/organization/'
      path: '/register/organization'
      fullPath: '/register/organization/'
      preLoaderRoute: typeof GuestRegisterOrganizationIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register/verify-email/': {
      id: '/_guest/register/verify-email/'
      path: '/register/verify-email'
      fullPath: '/register/verify-email/'
      preLoaderRoute: typeof GuestRegisterVerifyEmailIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/_exam/exam/$testId/': {
      id: '/_auth/_exam/exam/$testId/'
      path: '/exam/$testId'
      fullPath: '/exam/$testId/'
      preLoaderRoute: typeof AuthExamExamTestIdIndexRouteImport
      parentRoute: typeof AuthExamRoute
    }
    '/_auth/_organization-and-individu/profile/referral/': {
      id: '/_auth/_organization-and-individu/profile/referral/'
      path: '/referral'
      fullPath: '/profile/referral/'
      preLoaderRoute: typeof AuthOrganizationAndIndividuProfileReferralIndexRouteImport
      parentRoute: typeof AuthOrganizationAndIndividuProfileRoute
    }
    '/_guest/register/invite/$token/': {
      id: '/_guest/register/invite/$token/'
      path: '/register/invite/$token'
      fullPath: '/register/invite/$token/'
      preLoaderRoute: typeof GuestRegisterInviteTokenIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/_organization-and-individu/joint/invite/$token/': {
      id: '/_auth/_organization-and-individu/joint/invite/$token/'
      path: '/joint/invite/$token'
      fullPath: '/joint/invite/$token/'
      preLoaderRoute: typeof AuthOrganizationAndIndividuJointInviteTokenIndexRouteImport
      parentRoute: typeof AuthOrganizationAndIndividuRoute
    }
  }
}

interface AuthExamRouteChildren {
  AuthExamExamTestIdIndexRoute: typeof AuthExamExamTestIdIndexRoute
}

const AuthExamRouteChildren: AuthExamRouteChildren = {
  AuthExamExamTestIdIndexRoute: AuthExamExamTestIdIndexRoute,
}

const AuthExamRouteWithChildren = AuthExamRoute._addFileChildren(
  AuthExamRouteChildren,
)

interface AuthIndividuRouteChildren {
  AuthIndividuPortalIndexRoute: typeof AuthIndividuPortalIndexRoute
  AuthIndividuTestHistoryIndexRoute: typeof AuthIndividuTestHistoryIndexRoute
  AuthIndividuTestIndexRoute: typeof AuthIndividuTestIndexRoute
}

const AuthIndividuRouteChildren: AuthIndividuRouteChildren = {
  AuthIndividuPortalIndexRoute: AuthIndividuPortalIndexRoute,
  AuthIndividuTestHistoryIndexRoute: AuthIndividuTestHistoryIndexRoute,
  AuthIndividuTestIndexRoute: AuthIndividuTestIndexRoute,
}

const AuthIndividuRouteWithChildren = AuthIndividuRoute._addFileChildren(
  AuthIndividuRouteChildren,
)

interface AuthOrganizationRouteChildren {
  AuthOrganizationDashboardIndexRoute: typeof AuthOrganizationDashboardIndexRoute
  AuthOrganizationMembersIndexRoute: typeof AuthOrganizationMembersIndexRoute
  AuthOrganizationSettingsIndexRoute: typeof AuthOrganizationSettingsIndexRoute
}

const AuthOrganizationRouteChildren: AuthOrganizationRouteChildren = {
  AuthOrganizationDashboardIndexRoute: AuthOrganizationDashboardIndexRoute,
  AuthOrganizationMembersIndexRoute: AuthOrganizationMembersIndexRoute,
  AuthOrganizationSettingsIndexRoute: AuthOrganizationSettingsIndexRoute,
}

const AuthOrganizationRouteWithChildren =
  AuthOrganizationRoute._addFileChildren(AuthOrganizationRouteChildren)

interface AuthOrganizationAndIndividuProfileRouteChildren {
  AuthOrganizationAndIndividuProfileIndexRoute: typeof AuthOrganizationAndIndividuProfileIndexRoute
  AuthOrganizationAndIndividuProfileReferralIndexRoute: typeof AuthOrganizationAndIndividuProfileReferralIndexRoute
}

const AuthOrganizationAndIndividuProfileRouteChildren: AuthOrganizationAndIndividuProfileRouteChildren =
  {
    AuthOrganizationAndIndividuProfileIndexRoute:
      AuthOrganizationAndIndividuProfileIndexRoute,
    AuthOrganizationAndIndividuProfileReferralIndexRoute:
      AuthOrganizationAndIndividuProfileReferralIndexRoute,
  }

const AuthOrganizationAndIndividuProfileRouteWithChildren =
  AuthOrganizationAndIndividuProfileRoute._addFileChildren(
    AuthOrganizationAndIndividuProfileRouteChildren,
  )

interface AuthOrganizationAndIndividuRouteChildren {
  AuthOrganizationAndIndividuProfileRoute: typeof AuthOrganizationAndIndividuProfileRouteWithChildren
  AuthOrganizationAndIndividuBillingIndexRoute: typeof AuthOrganizationAndIndividuBillingIndexRoute
  AuthOrganizationAndIndividuJointInviteTokenIndexRoute: typeof AuthOrganizationAndIndividuJointInviteTokenIndexRoute
}

const AuthOrganizationAndIndividuRouteChildren: AuthOrganizationAndIndividuRouteChildren =
  {
    AuthOrganizationAndIndividuProfileRoute:
      AuthOrganizationAndIndividuProfileRouteWithChildren,
    AuthOrganizationAndIndividuBillingIndexRoute:
      AuthOrganizationAndIndividuBillingIndexRoute,
    AuthOrganizationAndIndividuJointInviteTokenIndexRoute:
      AuthOrganizationAndIndividuJointInviteTokenIndexRoute,
  }

const AuthOrganizationAndIndividuRouteWithChildren =
  AuthOrganizationAndIndividuRoute._addFileChildren(
    AuthOrganizationAndIndividuRouteChildren,
  )

interface AuthRouteChildren {
  AuthExamRoute: typeof AuthExamRouteWithChildren
  AuthIndividuRoute: typeof AuthIndividuRouteWithChildren
  AuthOrganizationRoute: typeof AuthOrganizationRouteWithChildren
  AuthOrganizationAndIndividuRoute: typeof AuthOrganizationAndIndividuRouteWithChildren
  AuthCreateOrganizationIndexRoute: typeof AuthCreateOrganizationIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthExamRoute: AuthExamRouteWithChildren,
  AuthIndividuRoute: AuthIndividuRouteWithChildren,
  AuthOrganizationRoute: AuthOrganizationRouteWithChildren,
  AuthOrganizationAndIndividuRoute:
    AuthOrganizationAndIndividuRouteWithChildren,
  AuthCreateOrganizationIndexRoute: AuthCreateOrganizationIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestIndexRoute: typeof GuestIndexRoute
  GuestForgotPasswordIndexRoute: typeof GuestForgotPasswordIndexRoute
  GuestLoginIndexRoute: typeof GuestLoginIndexRoute
  GuestRegisterIndexRoute: typeof GuestRegisterIndexRoute
  GuestResetPasswordIndexRoute: typeof GuestResetPasswordIndexRoute
  GuestRegisterOrganizationIndexRoute: typeof GuestRegisterOrganizationIndexRoute
  GuestRegisterVerifyEmailIndexRoute: typeof GuestRegisterVerifyEmailIndexRoute
  GuestRegisterInviteTokenIndexRoute: typeof GuestRegisterInviteTokenIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestIndexRoute: GuestIndexRoute,
  GuestForgotPasswordIndexRoute: GuestForgotPasswordIndexRoute,
  GuestLoginIndexRoute: GuestLoginIndexRoute,
  GuestRegisterIndexRoute: GuestRegisterIndexRoute,
  GuestResetPasswordIndexRoute: GuestResetPasswordIndexRoute,
  GuestRegisterOrganizationIndexRoute: GuestRegisterOrganizationIndexRoute,
  GuestRegisterVerifyEmailIndexRoute: GuestRegisterVerifyEmailIndexRoute,
  GuestRegisterInviteTokenIndexRoute: GuestRegisterInviteTokenIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
